CREATE TABLE Heroes (Id INT, Name VARCHAR(250))
INSERT INTO Heroes VALUES (1, 'Anti-Mage')
INSERT INTO Heroes VALUES (2, 'Axe')
INSERT INTO Heroes VALUES (3, 'Bane')
INSERT INTO Heroes VALUES (4, 'Bloodseeker')
INSERT INTO Heroes VALUES (5, 'Crystal Maiden')
INSERT INTO Heroes VALUES (6, 'Drow Ranger')
INSERT INTO Heroes VALUES (7, 'Earthshaker')
INSERT INTO Heroes VALUES (8, 'Juggernaut')
INSERT INTO Heroes VALUES (9, 'Mirana')
INSERT INTO Heroes VALUES (10, 'Morphling')
INSERT INTO Heroes VALUES (11, 'Shadow Fiend')
INSERT INTO Heroes VALUES (12, 'Phantom Lancer')
INSERT INTO Heroes VALUES (13, 'Puck')
INSERT INTO Heroes VALUES (14, 'Pudge')
INSERT INTO Heroes VALUES (15, 'Razor')
INSERT INTO Heroes VALUES (16, 'Sand King')
INSERT INTO Heroes VALUES (17, 'Storm Spirit')
INSERT INTO Heroes VALUES (18, 'Sven')
INSERT INTO Heroes VALUES (19, 'Tiny')
INSERT INTO Heroes VALUES (20, 'Vengeful Spirit')
INSERT INTO Heroes VALUES (21, 'Windranger')
INSERT INTO Heroes VALUES (22, 'Zeus')
INSERT INTO Heroes VALUES (23, 'Kunkka')
INSERT INTO Heroes VALUES (25, 'Lina')
INSERT INTO Heroes VALUES (26, 'Lion')
INSERT INTO Heroes VALUES (27, 'Shadow Shaman')
INSERT INTO Heroes VALUES (28, 'Slardar')
INSERT INTO Heroes VALUES (29, 'Tidehunter')
INSERT INTO Heroes VALUES (30, 'Witch Doctor')
INSERT INTO Heroes VALUES (31, 'Lich')
INSERT INTO Heroes VALUES (32, 'Riki')
INSERT INTO Heroes VALUES (33, 'Enigma')
INSERT INTO Heroes VALUES (34, 'Tinker')
INSERT INTO Heroes VALUES (35, 'Sniper')
INSERT INTO Heroes VALUES (36, 'Necrophos')
INSERT INTO Heroes VALUES (37, 'Warlock')
INSERT INTO Heroes VALUES (38, 'Beastmaster')
INSERT INTO Heroes VALUES (39, 'Queen of Pain')
INSERT INTO Heroes VALUES (40, 'Venomancer')
INSERT INTO Heroes VALUES (41, 'Faceless Void')
INSERT INTO Heroes VALUES (42, 'Wraith King')
INSERT INTO Heroes VALUES (43, 'Death Prophet')
INSERT INTO Heroes VALUES (44, 'Phantom Assassin')
INSERT INTO Heroes VALUES (45, 'Pugna')
INSERT INTO Heroes VALUES (46, 'Templar Assassin')
INSERT INTO Heroes VALUES (47, 'Viper')
INSERT INTO Heroes VALUES (48, 'Luna')
INSERT INTO Heroes VALUES (49, 'Dragon Knight')
INSERT INTO Heroes VALUES (50, 'Dazzle')
INSERT INTO Heroes VALUES (51, 'Clockwerk')
INSERT INTO Heroes VALUES (52, 'Leshrac')
INSERT INTO Heroes VALUES (53, 'Nature''s Prophet')
INSERT INTO Heroes VALUES (54, 'Lifestealer')
INSERT INTO Heroes VALUES (55, 'Dark Seer')
INSERT INTO Heroes VALUES (56, 'Clinkz')
INSERT INTO Heroes VALUES (57, 'Omniknight')
INSERT INTO Heroes VALUES (58, 'Enchantress')
INSERT INTO Heroes VALUES (59, 'Huskar')
INSERT INTO Heroes VALUES (60, 'Night Stalker')
INSERT INTO Heroes VALUES (61, 'Broodmother')
INSERT INTO Heroes VALUES (62, 'Bounty Hunter')
INSERT INTO Heroes VALUES (63, 'Weaver')
INSERT INTO Heroes VALUES (64, 'Jakiro')
INSERT INTO Heroes VALUES (65, 'Batrider')
INSERT INTO Heroes VALUES (66, 'Chen')
INSERT INTO Heroes VALUES (67, 'Spectre')
INSERT INTO Heroes VALUES (68, 'Ancient Apparition')
INSERT INTO Heroes VALUES (69, 'Doom')
INSERT INTO Heroes VALUES (70, 'Ursa')
INSERT INTO Heroes VALUES (71, 'Spirit Breaker')
INSERT INTO Heroes VALUES (72, 'Gyrocopter')
INSERT INTO Heroes VALUES (73, 'Alchemist')
INSERT INTO Heroes VALUES (74, 'Invoker')
INSERT INTO Heroes VALUES (75, 'Silencer')
INSERT INTO Heroes VALUES (76, 'Outworld Devourer')
INSERT INTO Heroes VALUES (77, 'Lycan')
INSERT INTO Heroes VALUES (78, 'Brewmaster')
INSERT INTO Heroes VALUES (79, 'Shadow Demon')
INSERT INTO Heroes VALUES (80, 'Lone Druid')
INSERT INTO Heroes VALUES (81, 'Chaos Knight')
INSERT INTO Heroes VALUES (82, 'Meepo')
INSERT INTO Heroes VALUES (83, 'Treant Protector')
INSERT INTO Heroes VALUES (84, 'Ogre Magi')
INSERT INTO Heroes VALUES (85, 'Undying')
INSERT INTO Heroes VALUES (86, 'Rubick')
INSERT INTO Heroes VALUES (87, 'Disruptor')
INSERT INTO Heroes VALUES (88, 'Nyx Assassin')
INSERT INTO Heroes VALUES (89, 'Naga Siren')
INSERT INTO Heroes VALUES (90, 'Keeper of the Light')
INSERT INTO Heroes VALUES (91, 'Io')
INSERT INTO Heroes VALUES (92, 'Visage')
INSERT INTO Heroes VALUES (93, 'Slark')
INSERT INTO Heroes VALUES (94, 'Medusa')
INSERT INTO Heroes VALUES (95, 'Troll Warlord')
INSERT INTO Heroes VALUES (96, 'Centaur Warrunner')
INSERT INTO Heroes VALUES (97, 'Magnus')
INSERT INTO Heroes VALUES (98, 'Timbersaw')
INSERT INTO Heroes VALUES (99, 'Bristleback')
INSERT INTO Heroes VALUES (100, 'Tusk')
INSERT INTO Heroes VALUES (101, 'Skywrath Mage')
INSERT INTO Heroes VALUES (102, 'Abaddon')
INSERT INTO Heroes VALUES (103, 'Elder Titan')
INSERT INTO Heroes VALUES (104, 'Legion Commander')
INSERT INTO Heroes VALUES (105, 'Techies')
INSERT INTO Heroes VALUES (106, 'Ember Spirit')
INSERT INTO Heroes VALUES (107, 'Earth Spirit')
INSERT INTO Heroes VALUES (108, 'Underlord')
INSERT INTO Heroes VALUES (109, 'Terrorblade')
INSERT INTO Heroes VALUES (110, 'Phoenix')
INSERT INTO Heroes VALUES (111, 'Oracle')
INSERT INTO Heroes VALUES (112, 'Winter Wyvern')
INSERT INTO Heroes VALUES (113, 'Arc Warden')
INSERT INTO Heroes VALUES (114, 'Monkey King')
INSERT INTO Heroes VALUES (119, 'Dark Willow')
INSERT INTO Heroes VALUES (120, 'Pangolier')
INSERT INTO Heroes VALUES (121, 'Grimstroke')
INSERT INTO Heroes VALUES (126, 'Void Spirit')
INSERT INTO Heroes VALUES (128, 'Snapfire')
INSERT INTO Heroes VALUES (129, 'Mars')
