CREATE TABLE GameModes (Id INT, Name VARCHAR(250))
INSERT INTO GameModes VALUES (0, 'Unknown')
INSERT INTO GameModes VALUES (1, 'All Pick')
INSERT INTO GameModes VALUES (2, 'Captain''s Mode')
INSERT INTO GameModes VALUES (3, 'Random Draft')
INSERT INTO GameModes VALUES (4, 'Single Draft')
INSERT INTO GameModes VALUES (5, 'All Random')
INSERT INTO GameModes VALUES (6, 'Intro')
INSERT INTO GameModes VALUES (7, 'Diretide')
INSERT INTO GameModes VALUES (8, 'Reverse Captain''s Mode')
INSERT INTO GameModes VALUES (9, 'Greeviling')
INSERT INTO GameModes VALUES (10, 'Tutorial')
INSERT INTO GameModes VALUES (11, 'Mid Only')
INSERT INTO GameModes VALUES (12, 'Least Played')
INSERT INTO GameModes VALUES (13, 'Limited Heroes')
INSERT INTO GameModes VALUES (14, 'Compendium Matchmaking')
INSERT INTO GameModes VALUES (15, 'Custom')
INSERT INTO GameModes VALUES (16, 'Captain''s Draft')
INSERT INTO GameModes VALUES (17, 'Balanced Draft')
INSERT INTO GameModes VALUES (18, 'Ability Draft')
INSERT INTO GameModes VALUES (19, 'Event')
INSERT INTO GameModes VALUES (20, 'ARDM')
INSERT INTO GameModes VALUES (21, '1v1 Mid')
INSERT INTO GameModes VALUES (22, 'All Draft')
INSERT INTO GameModes VALUES (23, 'Turbo')
INSERT INTO GameModes VALUES (24, 'Mutation')
