CREATE TABLE LobbyTypes (Id INT, Name VARCHAR(250))
INSERT INTO LobbyTypes VALUES (0, 'Normal')
INSERT INTO LobbyTypes VALUES (1, 'Practice')
INSERT INTO LobbyTypes VALUES (2, 'Tournament')
INSERT INTO LobbyTypes VALUES (3, 'Tutorial')
INSERT INTO LobbyTypes VALUES (4, 'Coop Bots')
INSERT INTO LobbyTypes VALUES (5, 'Ranked Team MM')
INSERT INTO LobbyTypes VALUES (6, 'Ranked Solo MM')
INSERT INTO LobbyTypes VALUES (7, 'Ranked')
INSERT INTO LobbyTypes VALUES (8, '1v1 Mid')
INSERT INTO LobbyTypes VALUES (9, 'Battle Cup')